import type { Metadata } from "next";
import "./globals.css";
import "highlight.js/styles/tokyo-night-dark.css";
import Footer from "./components/Footer";
import Header from "./components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased min-h-screen flex flex-col mx-auto w-1/2 bg-background text-foreground`}
      >
        <Header className="my-8" />
        <main className="flex-1">{children}</main>
        <Footer className="flex justify-center items-center h-24" />
      </body>
    </html>
  );
}
