import type { Metadata } from "next";
import { Audiowide, Rubik_Lines } from "next/font/google";
import "./globals.css";
import "highlight.js/styles/tokyo-night-dark.css";
import Footer from "../components/Footer";
import Header from "../components/Header";

// Fonts
const rubikPixelsFont = Rubik_Lines({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-rubik-lines",
});

const audiowideFont = Audiowide({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-audiowide",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${audiowideFont.variable} ${rubikPixelsFont.variable}`}
    >
      <body
        className={`bg-background text-foreground font-base mx-auto flex min-h-screen w-1/2 flex-col antialiased`}
      >
        <Header className="my-8" />
        <main className="flex-1">{children}</main>
        <Footer className="flex h-24 items-center justify-center" />
      </body>
    </html>
  );
}
